functioning /teachers/info endpoint
pedroalonsoms/ecoa pull request #101
Opened 2023-05-02 21:44 UTC by galactickem

2023-05-02 22:42 UTC, pedroalonsoms requested changes

2023-05-02 22:42 UTC, pedroalonsoms commented on server/src/routers/teacher-router.js
> +    res.status(500).send({ error: error.message || "Unknown error" });
Es status 400

2023-05-03 02:55 UTC, galactickem commented on server/src/routers/teacher-router.js
> +    res.status(500).send({ error: error.message || "Unknown error" });
Ya

2023-05-03 04:14 UTC, pedroalonsoms approved these changes

2023-05-03 04:14 UTC, merged