updating answers and finish
pedroalonsoms/ecoa pull request #32
Opened 2023-04-26 20:47 UTC by kerimtaray

2023-04-26 22:01 UTC, pedroalonsoms commented
Acepta la invite de GitHub

2023-04-27 07:10 UTC, pedroalonsoms requested changes
Ya casi queda. Hice una revisión a detalle, me gustó la lógica del endpoint de `/finish`. Cuando termines pruébalo y avisale a @Felipegonac0.

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
`// GET /answers/:studentId/questions/:questionId` comments not needed

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
>      res.status(200).json(rows);
Antes de retornar, checa que haya siempre un resultado.
Puede ser que no haya TmpAnswer de la pregunta solicitada. (En el caso que aún no haya contestado, o que sea la primera pregunta). Osea, checa que `rows` no esté vacío.
Mandale un error con un mensaje diciendole que aún no ha contestado o algo así. También puede ser un objeto vacío.
Habla con @Felipegonac0 para ver qué se le acomoda mejor de retornar cuando no hay answer todavía.

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
En la linea `18`: 
`SELECT * FROM TmpAnswer JOIN Su...` no deberías estar retornando todo.
Habla con @Felipegonac0 para ver qué es lo que ocupa que le devuelvas.

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
>      console.error(error);
Elimina el `console.error()`

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
En la línea `38` hay espacio de más

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
Checa que este código corra local con la extensión. Falta corregir y probar los archivos `.rest` de estos endpoints

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
En la línea `38`:
Usa un `z.enum()`: `targetKind: z.string(),`.
Tenemos un archivo `constants.js`, checalo

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
En la línea `49`:
Antes de hacer el query, valida que esté bien lo que te mandaron.
Puede ser que te mande `TEACHER_REGISTRATION` y aún así, mandarte un `teacherRegistration: null`.

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
En la línea `54`:
Dijimos que ibamos a quitar 
`await pool.query("CALL transferTmpAnswersByStudentRegistration(?), [studentRegistration]);"`

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
>      res.status(201).json({ message: "Answer created successfully" });
El status 201 es inconsistente con los demás estados que tenemos.
Usa `res.sendStatus(200)`

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
>      res.status(200).json(rows);
Usa `.send()` en lugar de `.json()` para ser consistente con los otros endpoints

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
> +    res.status(500).send({ error: error.message || "Unknown error" });
El status `500` es inconsistente con los demás que tenemos, ¿No debería ser 400?

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/finish-router.js
Quitar primera línea de comentaro

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/finish-router.js
>      if (activeSurvey.length === 0) {
Cambia error a `There's no current active survey`

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/finish-router.js
>      // TODO: add validation where you can not `finish` if you didn't complete all of the active-survey questions
Remove comment

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/finish-router.js
Linea `23`: mayúscula

2023-04-27 07:10 UTC, pedroalonsoms commented on server/src/routers/finish-router.js
Linea `25`: mayúscula en AS

2023-04-27 20:32 UTC, pedroalonsoms requested changes

2023-04-27 20:32 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
> +      res.status(400).send({ error: "The requested question has not been answered." });
Aqui debe ser throw new Error()

2023-04-27 20:32 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
> +        teacherRegistration: z.string().nullable().refine(value => value !== null, {
Esto dejalo como `z.string().nullable()`. La validación qeu me refería imlpementala por fuera de zod. Si `targetKind = "TEACHER_REGISTRATION" entonces asegurate que el teacherRegistration no sea `null`. Lo mismo con el CRN

2023-04-27 20:32 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
> +    res.status(200).send({ message: "Answer created successfully" });
Nomás manda `sendStatus(200)`, sin el mesaje

2023-04-27 20:32 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
> +    } else {
El `else` quitalo, en el if de arriba pon un `return`.

2023-04-27 20:32 UTC, pedroalonsoms commented on server/src/routers/answers-router.rest
> +POST http://localhost:8080/api//answers/:studentRegistration/questions/:questionId
Esto no corre. Tienes doble diagonal `/`. Prueba todos los archivos `.rest` con la extensión de vscode

2023-04-27 20:32 UTC, pedroalonsoms commented on server/src/routers/answers-router.rest
> +GET  http://localhost:8080/api/answers/:studentRegistration/questions/:questionId
El GET no debería llevar POST data

2023-04-27 20:32 UTC, pedroalonsoms commented on server/src/routers/answers-router.js
Quita el asterisco en `SELECT`, nomás son los fields que ocupas

2023-04-27 22:44 UTC, kerimtaray commented on server/src/routers/answers-router.js
Quede con Felipe de mandarle todo en el JSON (yo le mando la estructura del JSON) y ya el elige.

2023-04-27 22:48 UTC, pedroalonsoms requested changes
Lo de la extensión REST es lo que falta, principalmente

2023-04-27 22:48 UTC, pedroalonsoms commented on server/src/routers/answers-router.rest
> +GET http://localhost:8080/answers/{{studentRegistration}}/questions/{{questionId}}
Ponle una `studentRegistration` de ejemplo y una `questionId` de ejemplo. Corre el archivo `.rest`. Cuando instalas la extensión de REST que mandé por el grupo, te aparece un botón de `sendRequest` encima de tu editor de código. Asegurate de probar que este archivo funciona antes de mandarlo

2023-04-27 22:48 UTC, pedroalonsoms commented on server/src/routers/answers-router.rest
> +Content-Type: application/json
Esa no es la sintáxis, checa: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

2023-04-27 22:48 UTC, pedroalonsoms commented on server/src/routers/answers-router.rest
> +  "content": "{{content}}"
No deberías poner `{{}}` curly braces. Checa la sintáxis. Pon datos de ejemplo y verifica que corra. @Felipegonac0 va a necesitar esto para hacer query's a la API en su laptop local

2023-04-27 23:05 UTC, pedroalonsoms approved these changes
LGTM

2023-04-27 23:05 UTC, merged